name: lab Ci-pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y clang-format make

      - name: Check formatting for all labs
        run: |
          cd lab1 && make check_fmt
          cd ../lab2 && make check_fmt
          
      - name: Lab 1 Run tests
        working-directory: lab1
        run: make run_tests

      - name: Lab 2 Run tests
        working-directory: lab2
        run: make run_tests